
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
  
frontend:
    themes: !include_dir_merge_named themes
    extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
switch: !include switch.yaml


    
homeassistant:
  packages: !include_dir_named packages
  customize: !include customize.yaml
  customize_glob:
    "sensor.*":
      last_seen: null
    "binary_sensor.*":
      last_seen: null
    "switch.*":
      last_seen: null
    "light.*":
      last_seen: null
    "lock.*":
      last_seen: null
    "cover.*":
      last_seen: null
    "fan.*":
      last_seen: null
    "climate.*":
      last_seen: null
    

homekit:        
        
tts:
  - platform: google_translate

trace:
  stored_traces: 20 
        
notify:
  - platform: tts
    name: living_room_notify
    entity_id: tts.google_en_com
    media_player: media_player.family_room_speaker
    
shell_command:
  pushupdates_to_github: /bin/bash pushupdates.sh
            
logbook:
  exclude:
    entity_globs:
      - sensor.*_last_seen
      - binary_sensor.*_last_seen  
      - sensor.*_node_status
      - sensor.*_power_management