### SmartGateways.nl DistanceMeter Gateway - MQTT Connection
mqtt:
  sensor:
    - name: "connectix_distancemeter_realtime"
      state_topic: "distancemeter/reading/realtime_distance"
      unit_of_measurement: "cm"
      force_update: true
    - name: "connectix_distancemeter_average"
      state_topic: "distancemeter/reading/average_distance"
      unit_of_measurement: "cm"
      force_update: true

    - name: "connectix_distancemeter_entered_hight"
      state_topic: "distancemeter/reading/entered_hight"
      unit_of_measurement: "cm"
      force_update: true
    - name: "connectix_distancemeter_entered_offset"
      state_topic: "distancemeter/reading/entered_offset"
      unit_of_measurement: "cm"
      force_update: true

    - name: "connectix_distancemeter_corrected_distance"
      state_topic: "distancemeter/reading/corrected_distance"
      unit_of_measurement: "cm"
      force_update: true
    - name: "connectix_distancemeter_percentage_full"
      state_topic: "distancemeter/reading/percentage_full"
      unit_of_measurement: "%"
      force_update: true
    - name: "connectix_distancemeter_level_full"
      state_topic: "distancemeter/reading/level_full"
      unit_of_measurement: "cm"
      force_update: true
      
      
    - name: "Distancemeter MAC Adres"
      state_topic: "distancemeter/smart_gateways/mac_address"
    - name: "Distancemeter Gateway IP Address"
      state_topic: "distancemeter/smart_gateways/ip_address"
    - name: "Distancemeter Firmware versie van gateway"
      state_topic: "distancemeter/smart_gateways/running_firmware_version"
    - name: "Distancemeter Beschikbare firmware versie"
      state_topic: "distancemeter/smart_gateways/available_firmware_version"
    - name: "Distancemeter Firmware update beschikbaar"
      state_topic: "distancemeter/smart_gateways/update_available"
    - name: "Distancemeter WiFi Signaalsterkte (rssi)"
      state_topic: "distancemeter/smart_gateways/wifi_rssi"
      unit_of_measurement: 'dB'
    - name: "Distancemeter startup time"
      state_topic: "distancemeter/smart_gateways/startup_time"
      device_class: timestamp
      icon: mdi:clock-start

### SmartGateways.nl Distancemeter Gateway - firmware update switch
  switch:
  - name: "Distancemeter Install firmware update?"
    command_topic: "distancemeter/smart_gateways/install_update"
    payload_on: "yes"
    payload_off: "no"

### SmartGateways.nl Distancemeter Gateway - Berekeningen
sensor:
  - platform: template
    sensors:
##  Distancemeter_last_changed
      distancemeter_lastchanged:
        value_template: >
          {% set values = [
            states.sensor.distancemeter_wifi_signaalsterkte_rssi.last_changed, ] %}
          {{ values | min }}
        device_class: timestamp

template:
  - binary_sensor:
      - name: "Distancemeter connectivity status"
        state: "{{ now() - states.sensor.distancemeter_wifi_signaalsterkte_rssi.last_changed < timedelta(minutes=10) }}"
        device_class: connectivity